---
all:
  children:
    ops:
      children:
        ops_root:
          vars:
            ansible_user: root
          children:
            repo_mirrors:
              hosts:
                repomirror6.massopen.cloud:
            ovirt_servers:
              hosts:
                ov1.massopen.cloud:
                ov2.massopen.cloud:
                ov3.massopen.cloud:
            dns_servers:
              hosts:
                ns1.massopen.cloud:
                ns2.massopen.cloud:
            mail_servers:
              hosts:
                mail.massopen.cloud:
            list_servers:
              hosts:
                lists.massopen.cloud:
            esi_ha_cluster:
              children:
                esi_undercloud:
                  hosts:
                    esi-undercloud.massopen.cloud:
                esi_controller:
                  vars:
                    ctlplane_interface: eth0
                  hosts:
                    esi-controller-0.massopen.cloud:
                    esi-controller-1.massopen.cloud:
                    esi-controller-2.massopen.cloud:
            osticket_servers:
              hosts:
                osticket.massopen.cloud:
          hosts:
            kumo-hil-client.infra.massopen.cloud:
        ops_other:
          children:
            freeipa_servers:
              hosts:
                freeipa.massopen.cloud:
                  ansible_remote_tmp: /tmp
